---
    - name: install tools
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - ipvsadm
        - keepalived

    - sysctl:
        name: net.ipv4.ip_forward
        sysctl_file: /etc/sysctl.conf
        value: 1
        reload: yes
        sysctl_set: yes
        state: present

    - sysctl:
        name: net.core.netdev_max_backlog
        sysctl_file: /etc/sysctl.conf
        value: 65535
        reload: yes
        sysctl_set: yes
        state: present

    - name: copy ip_vs.conf
      template:
        src: templates/ip_vs.conf
        dest: /etc/modprobe.d/ip_vs.conf

    - name: copy keepalived config
      template:
        dest: /etc/keepalived/keepalived.conf
        src: templates/keepalived.conf
      notify:
        - start keepalived