- name: kubectl label failure-domain.beta.kubernetes.io/region
  shell: "{{ SETUP_TOOLS_DIR }}/bin/kubectl --kubeconfig={{ CONTROL_BASE_DIR }}/admin.conf label node {{hostvars[item]['inventory_hostname']}} failure-domain.beta.kubernetes.io/region={{hostvars[item]['Region']}}"
  loop: "{{ groups['kube'] }}"

- name: kubectl label failure-domain.beta.kubernetes.io/zone
  shell: "{{ SETUP_TOOLS_DIR }}/bin/kubectl --kubeconfig={{ CONTROL_BASE_DIR }}/admin.conf label node {{hostvars[item]['inventory_hostname']}} failure-domain.beta.kubernetes.io/zone={{hostvars[item]['Zone']}}"
  loop: "{{ groups['kube'] }}"