- name: make /etc/kubernetes/pki/
  file:
    path: /etc/kubernetes/pki/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: make /etc/kubernetes/pki/etcd/
  file:
    path: /etc/kubernetes/pki/etcd/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy etcd certs
  copy:
    src: "{{ CONTROL_BASE_DIR }}/certs/etcd/{{ item.src }}"
    dest: "/etc/kubernetes/pki/{{ item.dest }}"
  loop:
    - { src: etcd-ca.pem, dest: etcd/ca.crt }
    - { src: etcd-client.pem, dest: apiserver-etcd-client.crt }
    - { src: etcd-client-key.pem, dest: apiserver-etcd-client.key }

- name: make /etc/kubernetes/init/
  file:
    path: /etc/kubernetes/init/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy kubeadm config
  template:
    src: templates/kubeadm-config.yaml
    dest: /etc/kubernetes/init/kubeadm-config.yaml